### ISSUE TITLE
colored input arrows

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/NeuronSandbox#15]
Right now the input arrows to the neuron are black. Let's make them red for negative weights, black for positive, and blue for zero.

Also, let's scale the thickness of the arrow based on the weight manitude, up to some reasonable limit like 6.0.

**Comment by neelpawarcmu** [comment]
Currently, the arrow colors look nice but it is not very intuitive as to what the colors mean. I think it would be nice to match the color of the weight text with that of the arrows?

**Comment by touretzkyds** [comment]
That's a good idea. @achenvc  can you try this?

**Comment by achenvc** [comment]
Got it! This feature should be added in the latest code.

**Comment by touretzkyds** [comment]
Looks great! I see the thickness scaling is also fixed, and the arrowheads are touching the circle now. And the color for the negative values is just right. Good job.
