### ISSUE TITLE
appearance issues; incorrect thresholding

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/NeuronSandbox#3]
1. The neuron diagram has an = sign inside the circle, after the sigma. This should be a > sign.
2. Eliminate the "y=" in the output display; just display the output value, not the activation value.
3. Change the output table headings to "activation" and "output" (singular, not plural).
4. The output is being computed incorrectly. The output should be 1 if the activation is GREATER THAN the threshold, not greater than or equal to.
5. If the user changes the value of a weight or threshold, the output table is updated correctly, but the output value shown in the neuron diagram is not updated.
6. While the user is hovering over a row of the input table, the x1/x2 labels in the diagram should be replaced with the corresponding values from the table. When the user moves the mouse out of the table, the x1/x2 labels should be restored and the output value in the diagram should be suppressed.

**Comment by neelpawarcmu** [comment]
Resolved
